// projects/front-react/src/pages/manager/forms/rule-test-form/RuleTestForm.tsx
import React from 'react'
import { Form, Input, message, Modal } from 'antd'
import { IBaseProps } from '../utils.ts'

// @ts-ignore
import './index.less'
import type { FormRef } from 'rc-field-form/lib/interface'
import HttpInput from './HttpInput.tsx'
import IRuleService, { IHttpApiInfo } from '../../service-api/IRuleService.ts'
import { getServiceSync } from '@spring4js/container-browser/lib/esm/global-fn'
import EService from '../../config/EService.ts'

export interface IProps extends IBaseProps {
  matchMethod: string // 匹配method
  matchUrl: string // 匹配url
  target: string // 转发末班
}

interface IState {}

type FieldType = {
  request: IHttpApiInfo
  match: IHttpApiInfo
  target: string // 转发目标
  matchResult: string // 匹配结果
  redirectResult: string // 转发结果
  message: string
}

const ruleService = getServiceSync<IRuleService>(EService.IRuleService)

export default class RuleTestForm extends React.PureComponent<IProps, IState> {
  formRef = React.createRef<FormRef<FieldType>>()
  initialValue: FieldType
  constructor(props: IProps) {
    super(props)
    this.initialValue = {
      request: {
        method: '',
        url: '',
      },
      match: {
        method: props.matchMethod,
        url: this.props.matchUrl,
      },

      target: props.target, // 转发目标
      matchResult: '', // 匹配结果
      redirectResult: '', // 转发结果
      message: '',
    }
  }
  async testMatchRule() {
    const values = this.formRef.current?.getFieldsValue()!
    try {
      const result = await ruleService.testRule(values.match, values.target, values.request)
      this.formRef.current?.setFieldsValue({
        matchResult: result.matchResult,
        redirectResult: result.redirectResult,
        message: result.message,
      })
    } catch (err: any) {
      message.error(`出错了，${err.message}`)
    }
  }

  render() {
    const { onCancel } = this.props
    return (
      <Modal
        title="匹配-转发 测试"
        open={true}
        okText="测试"
        onOk={() => this.testMatchRule()}
        cancelText="取消"
        onCancel={() => onCancel(undefined)}
      >
        <Form
          name="configure"
          ref={this.formRef}
          labelCol={{ span: 8 }}
          wrapperCol={{ span: 16 }}
          style={{ maxWidth: 600 }}
          initialValues={this.initialValue}
          autoComplete="off"
        >
          <Form.Item<FieldType> label="匹配规则" name="match">
            <HttpInput
              options={[
                { value: '', label: '所有' },
                { value: 'get', label: 'GET' },
                { value: 'post', label: 'POST' },
                { value: 'put', label: 'PUT' },
                { value: 'patch', label: 'PATCH' },
                { value: 'delete', label: 'DELETE' },
                { value: 'options', label: 'OPTIONS' },
              ]}
            />
          </Form.Item>
          <Form.Item<FieldType> label="转发路径" name="target">
            <Input />
          </Form.Item>
          <Form.Item<FieldType> label="请求" name="request">
            <HttpInput
              options={[
                { value: 'get', label: 'GET' },
                { value: 'post', label: 'POST' },
                { value: 'put', label: 'PUT' },
                { value: 'patch', label: 'PATCH' },
                { value: 'delete', label: 'DELETE' },
                { value: 'options', label: 'OPTIONS' },
              ]}
            />
          </Form.Item>
          <Form.Item<FieldType> label="匹配结果" name="matchResult">
            <Input disabled />
          </Form.Item>
          <Form.Item<FieldType> label="转发结果" name="redirectResult">
            <Input disabled />
          </Form.Item>
          <Form.Item<FieldType> label="其他信息" name="message">
            <Input.TextArea autoSize={{ minRows: 10, maxRows: 10 }} disabled />
          </Form.Item>
        </Form>
      </Modal>
    )
  }
}

// webui/src/manager/form-widget/rule-test-form/Index.vue
<template>
    <el-dialog title="匹配-转发 测试"
               :close-on-click-modal="false"
               :visible.sync="visible"
               width="800px">
        <div class="test-rule-form">
            <el-form :model="testMatchRuleForm"
                     label-width="120px">
                <el-form-item label="请求">
                    <el-select
                            v-model="testMatchRuleForm.requestMethod"
                            size="small"
                            placeholder="请选择">
                        <el-option v-for="item in requestMethodList"
                                   :key="item.value"
                                   :label="item.label"
                                   :value="item.value">
                        </el-option>
                    </el-select>
                    <el-input size="small"
                              v-model="testMatchRuleForm.requestUrl"></el-input>
                </el-form-item>
                <el-form-item label="匹配条件">
                    <el-select
                            v-model="testMatchRuleForm.matchMethod"
                            size="small"
                            placeholder="请选择">
                        <el-option v-for="item in matchMethodList"
                                   :key="item.value"
                                   :label="item.label"
                                   :value="item.value">
                        </el-option>
                    </el-select>
                    <el-input size="small"
                              v-model="testMatchRuleForm.matchUrl"></el-input>
                </el-form-item>
                <el-form-item label="转发路径">
                    <el-input size="small"
                              v-model="testMatchRuleForm.target"></el-input>
                </el-form-item>
                <el-form-item label="匹配结果">
                    <el-input size="small"
                              v-model="testMatchRuleForm.matchResult" :disabled="true"></el-input>
                </el-form-item>
                <el-form-item label="转发结果">
                    <el-input size="small"
                              v-model="testMatchRuleForm.redirectResult" :disabled="true"></el-input>
                </el-form-item>
                <el-form-item label="其他信息">
                    <el-input size="small"
                              v-model="testMatchRuleForm.message" type="textarea" :disabled="true"></el-input>
                </el-form-item>
            </el-form>
            <div class="bottom-action">
                <el-button @click="cancel">关 闭</el-button>
                <el-button type="primary" @click="testMatchRule">测 试</el-button>
            </div>
        </div>
    </el-dialog>
</template>

<script>
  import ruleApi from 'src/api/rule';
  import './rule-test-form.scss'

  export default {
    name: "RuleTestForm",
    components: {},
    data() {
      return {
        visible: true,
        testMatchRuleForm: {
          requestMethod: '',// 请求method
          requestUrl: '',// 请求url
          matchMethod: '',// 匹配method
          matchUrl: '',// 匹配url
          target: '', // 转发目标
          matchResult: '', // 匹配结果
          redirectResult: '',// 转发结果
          message: '',
        },
        matchMethodList: [
          {value: '', label: '所有'},
          {value: 'get', label: 'GET'},
          {value: 'post', label: 'POST'},
          {value: 'put', label: 'PUT'},
          {value: 'patch', label: 'PATCH'},
          {value: 'delete', label: 'DELETE'},
          {value: 'option', label: 'OPTION'}
        ],
        requestMethodList: [
          {value: 'get', label: 'GET'},
          {value: 'post', label: 'POST'},
          {value: 'put', label: 'PUT'},
          {value: 'patch', label: 'PATCH'},
          {value: 'delete', label: 'DELETE'},
          {value: 'option', label: 'OPTION'}
        ]
      }
    },
    methods: {
      cancel() {
        this.visible = false;
      },

      /**
       url: '',// 请求url
       urlMatch: '',// url匹配规则
       urlReg: '',// url的正则，用于路径替换
       targetTpl: '',// 路径模板， 会用urlReg的匹配结果来替换targetTpl $1 $2
       matchRlt:'',// url匹配结果
       targetRlt: ''// 路径匹配结果
       * @param row
       */
      testRule({
                 match, method, target
               }) {
        this.testMatchRuleForm = {
          requestMethod: '',// 请求method
          requestUrl: '',// 请求url
          matchMethod: method,// 匹配method
          matchUrl: match,// 匹配url
          target: target, // 转发末班
          matchResult: '', // 匹配结果
          redirectResult: '',// 转发结果
          message: '',
        };
        this.visible = true;
      },

      testMatchRule() {
        ruleApi.testRule(this.testMatchRuleForm).then((response) => {
          var serverData = response.data;
          if (serverData.code == 0) {
            this.testMatchRuleForm.matchResult = serverData.data.matchResult;
            this.testMatchRuleForm.redirectResult = serverData.data.redirectResult;
            this.testMatchRuleForm.message = serverData.data.message;
          }
        });
      }
    }
  }
</script>
