// projects/front-react/src/pages/manager/views/host/EditHost.tsx
import React from 'react';
import './edit-host.less';
import IHostService, { IHostFile } from '../../service-api/IHostService.ts';
import { Button, Col, Input, Row } from 'antd';
import { getQueryParams } from '../../../../common/query-string.ts';
import { getServiceSync } from '@spring4js/container-browser/lib/esm/global-fn';
import EService from '../../config/EService.ts';
import { produce } from 'immer';
interface IProps {}

interface IState {
  hostFileId: string;
  loaded: boolean;
  hostFile?: IHostFile;
}
const PlaceHolder = `#示例
8.8.8.8    www.google.com
4.4.4.4    *.taobao.com #所有后缀为.taobao.com的域名都被解析为4.4.4.4
6.6.6.6    www.youzan.com h5.youzan.com`;

const hostService = getServiceSync<IHostService>(EService.IHostService);

export default class EditHost extends React.PureComponent<IProps, IState> {
  state: IState = {
    hostFileId: '',
    loaded: false,
  };
  async componentDidMount() {
    this.loadHostFile();
  }
  componentWillUnmount() {}
  async loadHostFile() {
    const query = getQueryParams();
    const id = query.id;
    const content = await hostService.getFileContent(id);
    if (!content) {
      return;
    }
    this.setState({
      hostFileId: id,
      loaded: true,
      hostFile: content,
    });
  }

  async saveFile() {
    const { hostFile, hostFileId } = this.state;
    await hostService.saveFile(hostFileId, hostFile!);
  }
  onContentChange(content: string) {
    const { hostFile } = this.state;
    const newHostFile = produce(hostFile, (draft) => {
      draft!.content = content;
    });
    this.setState({
      hostFile: newHostFile,
    });
  }
  render() {
    const { hostFile, loaded } = this.state;
    return (
      <div>
        <div className="main-content__title">编辑Host文件{loaded ? ': ' + hostFile?.name : ''}</div>
        <Row>
          <Col span={6} offset={16}>
            <Button type="primary" onClick={() => this.saveFile()}>
              保存文件
            </Button>
          </Col>
        </Row>

        <Input.TextArea
          value={hostFile?.content}
          autoSize={{ minRows: 20, maxRows: 20 }}
          onChange={(e) => this.onContentChange(e.target.value)}
          placeholder={PlaceHolder}
        />
      </div>
    );
  }
}

// webui/src/manager/components/host/EditHost.vue
<template>
    <div>
        <div class="main-content__title">编辑Host文件{{ loaded ? ': ' + filecontent.name : '' }}</div>
        <el-row :gutter="20" style="margin-bottom: 10px">
            <el-col :span="6" :offset="18">
                <el-button size="small" type="primary" @click='saveFile'>保存文件</el-button>
            </el-col>
        </el-row>
        <textarea class="host-editor" :placeholder="hostExample" v-model="filecontent.content"></textarea>
    </div>
</template>

<script>
    import hostApi from '../../../api/host';
    import forEach from 'lodash/forEach';
    export default {
        name: 'app',
        data() {
            return {
                loaded: false,
                filecontent: {
                    content: ''
                }
            };
        },
        computed: {
            hostExample() {
                return `#示例
8.8.8.8    www.google.com
4.4.4.4    *.taobao.com #所有后缀为.taobao.com的域名都被解析为4.4.4.4
6.6.6.6    www.youzan.com h5.youzan.com`
            }
        },

        methods: {
            getFile() {
                this.loaded = false;
                hostApi.getFileContent(this.$route.query.name).then((response) => {
                    var serverData = response.data;
                    if (serverData.code == 0) {
                        this.loaded = true;
                        this.filecontent = serverData.data;
                        // 解析host数组
                        this.hostarray = [];
                        forEach(this.filecontent.content, (value, key) => {
                            this.hostarray.push({
                                key: key,
                                value: value
                            });
                        });
                    } else {
                        this.$message.error(`出错了，${serverData.msg}`);
                    }
                });
            },
            saveFile() {
                hostApi.saveFile(this.$route.query.name, this.filecontent).then((response) => {
                    var serverData = response.data;
                    if (serverData.code == 0) {
                        this.$message({
                            type: 'success',
                            message: '保存成功!'
                        });
                    } else {
                        this.$message.error(`出错了，${serverData.msg}`);
                    }
                });
            }
        },
        mounted() {
            this.getFile();
        },
        watch: {
            '$route'(to, from) {
                this.getFile();
            }
        }
    };

</script>
<style>
    .host-editor {
        height: 500px;
        width: 84%;
        font-size: 18px;
        padding: 10px 20px;
    }
</style>
